[package]
name = "blockfish"
version = "0.1.0"
authors = ["iitalics <iitalics@gmail.com>"]
edition = "2018"

[[bin]]
name = "blockfish-race"
path = "src/bin/race.rs"
required-features = ["block-stacker"]

[features]
default = []
slow-tests = []

[dependencies]
thiserror = "1.0"
log = "0.4.8"
rand = "0.7"
red_union_find = "0.2.5"

[dependencies.block-stacker]
path = "../block-stacker"
optional = true