[package]
name = "block-stacker"
version = "0.1.0"
authors = ["iitalics <iitalics@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
rand_pcg = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
